### PR TITLE
Use sendRedirectedMessage where possible

### PR DESCRIPTION
**Pull request by TheEpicBlock**
This helps slightly with compat, as some mods benefit from player context with packets.

### CODE REVIEW

**Comment by qouteall** [comment]
What do you mean by it helps compat? Do other mods inject immptl's `sendRedirectedMessage`?

**Comment by TheEpicBlock** [comment]
I'm currently mixing into that method as it's the only real place to insert player context before the packet is written. The other solution would be to mixin to ServerGamePacketListenerImpl, deserialize the packets, and then write them again but with the correct context.

**Comment by Patbox** [comment]
Which is kinda thing I'm doing in https://github.com/Patbox/polymer/tree/dev/1.18.2/polymer/src/main/java/eu/pb4/polymer/mixin/compat/immersive_portals
This would be really helpful for making it faster!
Ideally IMP could fully move serialization to networking thread, but this would require some work

**Comment by qouteall** [comment]
I see

**Pull request merged**
