### PR TITLE
Added Set NBT Command for command blocks

### PR DESCRIPTION
**Pull request by JoelOsler**
I wanted to edit custom named portal nbt data, but you normally have to look at the portal, so I mixed the set portal nbt data command and one of the command block commands to create this!

Also my editor thought it was a good idea to auto format all of the code in the file, so yeah, its formatted now.

### CODE REVIEW

**Comment by qouteall** [comment]
The command is good. However, it reformated so much and the format is weird. It's recommended to redo this pr without auto reformatting

**Comment by JoelOsler** [comment]
Ok! I will revert it and disable my auto formatter.
I’ll do it tomorrow as it is very late now.

**Review by JoelOsler — COMMENTED** [review]
Re-added the code, without formatting.

**Comment by JoelOsler** [comment]
Also merged the new changes onto my local copy, took a while to figure it out.

**Comment by qouteall** [comment]
The reformatting is still in the pr. And why does github show the unrelated changes, that's weird

**Comment by qouteall** [comment]
https://github.com/qouteall/ImmersivePortalsMod/compare/1.16...JoelOsler:1.16

**Review by JoelOsler — COMMENTED** [review]
I think I got it this time!

**Pull request merged**
