### PR TITLE
Add the ability to customize the Dimension Stack Divider

### PR DESCRIPTION
**Pull request by froyo4u**
Please note: it does require a restart to take affect at the moment.

### CODE REVIEW

**Comment by qouteall** [comment]
Maybe some people need to customize different bedrock blocks for different dimensions

**Comment by qouteall** [comment]
And seems that vanilla supports a block processor system. https://minecraft.gamepedia.com/Custom_world_generation/processor_list
I am thinking whether it can be used for replacing bedrock

**Comment by froyo4u** [comment]
What specifically do you mean by that? Like the ability to change it for each specific dim?

**Comment by qouteall** [comment]
Yes

**Comment by qouteall** [comment]
What? That pr contains this pr?

**Comment by froyo4u** [comment]
Wtf why, it was literally a different branch

**Pull request merged**
