### PR TITLE
Miss portal placeholders

### PR DESCRIPTION
**Pull request by LoganDark**
It's quite simple really.

PortalPlaceholder blocks simply no longer collide with raycasts, so ALL raycasts completely go through them.

It's now impossible to select one and you no longer need to have these edge cases that detect a portal placeholder block being there.

<s>Con: Since mixin is crap, I can't <code>@Redirect</code> a default method in an interface, so I have to copy and paste it, which is absolutely ridiculous.

Pro:</s> You never have to worry about hit results being portal placeholders ever again.

image

On this stone block is a portal placeholder I created using setblock. As you can see I'm aiming right through it.

You can no longer accidentally break nether portals in creative by left clicking while being in the center of the portal.

### CODE REVIEW

**Comment by LoganDark** [comment]
Tested and it works perfectly

**Comment by qouteall** [comment]
There is one issue that when the player removes a nether portal using command, the placeholder blocks remain and player cannot break them in creative.

**Comment by LoganDark** [comment]
> the placeholder blocks remain and player cannot break them in creative.

That can be fixed by making the placeholder blocks remove themselves if they aren't part of a portal. Let me know if you want to do this or if you want me to.

**Comment by qouteall** [comment]
A solution is to make placeholder untargettable only when it's colliding with a portal.

**Comment by LoganDark** [comment]
I suppose that's a better solution. However right now I don't think there's any way to check if a certain block is colliding with a portal. Do you have any ideas?

**Comment by LoganDark** [comment]
Also there's that nether entity issue which currently makes it impossible to detect portals in the nether, so aiming through a nether portal would break.

**Comment by qouteall** [comment]
Normally you can use world.getEntities but it's not designed to work with large entities. It's better to use McHelper#getEntitiesRegardingLargeEntities

**Comment by qouteall** [comment]
And I think that the special treatment for placeholder block should remain in aiming through portal code

**Comment by LoganDark** [comment]
> Normally you can use world.getEntities but it's not designed to work with large entities. It's better to use McHelper#getEntitiesRegardingLargeEntities

You actually can't because for some reason the McHelper methods don't see entities in other worlds.

That currently causes an issue in my recursive aim branch because you somehow can't see entities in other worlds. It's a weird issue.

**Comment by LoganDark** [comment]
These changes have been added by #206

**Pull request closed without merging**
